### ISSUE TITLE
Opt-in EE.log parsing

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/WFinfo#10]
Must be able to opt-in and opt-out easily
Likely a check box in Settings.vb with a popup confirmation/explanation

**Comment by dapal-003** [comment]
Opt-in is easily possible, currently no way to "opt-out". Not activating auto mode will not spawn the watcher for the log file but it's not clear to the user that we're no longer monitoring the file.

**Comment by dimon222** [comment]
@dapal-003 does it even make sense to monitor logfile realtime? Why not parse last 200 lines in logfile when user clicks hotkey? Similar to parsing with tesseract on hotkey instead parse the logfile on hotkey action.

**Comment by dapal-003** [comment]
The whole reason we dipped our toes into monitoring the ee.log file was in order to specify when the relics screen was visible. Which would allow us to run the scan on the screen. 

The old way of "detecting" if there was any rewards on screen was to take a screenshot every second and then see if the rewards UI was shown on it. This caused many issues (Some of them are: [Mouse movement stutters](https://github.com/WFCD/WFinfo/issues/29) and [issues with autoclickers](https://github.com/WFCD/WFinfo/issues/27)) 

logging a text file in real time has a much lower performance impact to taking a screenshot every second. Thus the switch was made, this wasn't perfect as the log doesn't always tell exactly when the screen is shown and also gives false positives.

**Comment by dimon222** [comment]
I see, so the rewards are on screen only, they never land in EE.log. Perhaps the expression can be tuned to give less false positives (that triggers for rewards screen).

So far my own experience seem to refer to fact that reward screen opens just too fast, theoretically it can improved by simply longer delay before detection vs scan on screen. Perhaps, extra couple of seconds.

**Comment by dapal-003** [comment]
They never specifically drop in EE.log. [This](https://i.imgur.com/xM0EHTN.png) is what gets dumped into EE.log when a relic is opened. We currently are looking for "Sys [Info]: Created /Lotus/Interface/ProjectionsCountdown.swf" to trigger the auto mode. The problem with this is that it's also depended on lag from the host. (And thus currently doesn't work well)

There was work done on a configurable timer using .json files but this was put on hold when we decided to switch to re-basing our program to C#

**Comment by dimon222** [comment]
This is adjusted in v9 as standard option "Auto" in settings.
