### ISSUE TITLE
"Faked" Inventory

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/WFinfo#14]
![image](https://user-images.githubusercontent.com/7128721/71786867-57c11580-2fd6-11ea-9315-3c3d826485c0.png)

**Comment by dapal-003** [comment]
A re-write to the current equipment and relic screen. A more streamlined UI would be needed, possibly in the style of Warframe?

**Comment by dapal-003** [comment]
Currently thinking about implementing it in the following way:

* Refactor the old system from "Owned" to "Mastered" 
* A new button would be added to the main window to open up a list of items which have multiple columns.
* These could change but these would make the most sense for me: "Owned, Plat, Ducats, Plat/Ducats, volume
 * Items not marked as "Mastered" would show up as a dull grey
* Right clicking on an item would show a context menu with the following items:
 * Remove 1
 * Add 1
 * Change Owned, which will then pop up a dialog where the user can type in a number.
 * List on warframe.market (This would be implemented on a later date, but would pop up a dialog with more info about how much the particular item has gone for + the ability to actually post it to your account. 
* Having a "Set detection" could be useful, as sets sell on average for more than the sum of the parts. 

With Warframe.market integration we could also implement a second tab, of all current active listings. Making it easier to manage those as well. However, I feel like that is starving too far away from this current feature. 

Feedback would be appreciated on the structure.

**Comment by carnufex** [comment]
I would probably just save it as a json object to file and then read it into a dictionary within the program itself. depending on size and memory usage.
Regarding the fields in the structure I feel that I'm way to inexperienced in Warframe to give any decent advice. 
Using an object structure its no cost to add/remove fields anyhow.
fields for: owned, amount, plat, ducats and a color indicator for mastered seems nice and a good start tho.

Removing stuff would however require manual input, if you wouldnt want to reset the whole Equipment tab for rescanning using OCR method.
If Warframe has an API to reach the inventory that kind of solution would be far superior, but I'm not aware of such an API.

Market integration would be nice but should be put into another ticket, with way lower priority.

**Comment by tboby** [comment]
It seems like there might be a few different use-cases here:
1. Somebody entering/updating their entire inventory
2. Somebody quickly updating after opening a relic or selling an item
3. Somebody looking for specific information (if they've completed a set, what items they should ducat, if they have any sets to sell)

And with two screens

- Equipment: For when you're playing
- Inventory: For when you're trading/updating in bulk
there would still be a bit of duplication of ways of doing things, but maybe that's not a problem?

In a dream world 1 would be automated, but until then it would be good to make sure bulk entry and quick updates are both fast. I'd suggest keeping the + and - buttons, but when the user clicks on the current count let them type directly.

>Owned, Plat, Ducats, Plat/Ducats, volume

I would be tempted to suggest that "Plats/ducat" and "volume" be toggle-able in order to keep the UI thin.

On "Owned"/"Mastered", should sets and items be treated differently?

- Sets: Conceptually, a set is either "uncrafted", "crafted" or "mastered". There's also an implicit state of "I own all the bits but haven't crafted it yet". But I guess that can be covered by the "Set" counter?
- Items: An item is just owned, with a count of how many. However, an item can be part of a set that is "crafted/mastered", and coloured by that.

> Items not marked as "Mastered" would show up as a dull grey

On the equipment screen, you want "Mastered" to be dull grey, so are the equipment screen and the inventory screen opposites? A lot of the same data, just presented in a different way?
