### ISSUE TITLE
wfinfo cant understand text with Dark lotus ui theme

### ISSUE THREAD

**Issue by ghost** [WFCD/WFinfo#215]
**Describe the bug**
Soo i was using wfinfo 9.4.2 for like a month or something like that and i had 0 problems i was using stalker ui theme and it was all good
but now i bought dark lotus ui theme and i started to get not accurate prices it like sees other names instead of true names
also i tested it with 50 bright and contrast 50, 50 bright and 30 contrast. nothing changes same error
**To Reproduce**
1. Go to options
2. Click on interface
3. Click on UI Customization
4. Click on Theme
5. Equip Dark Lotus Theme
6. Now play Void fissure
7. Check at the extraction what prices and for what items WFInfo displays info

**Expected behavior**
To display correct information

**Screenshots**
![Безымянный123123](https://user-images.githubusercontent.com/37495772/145812256-3f6b665a-2918-44c4-a2e3-e46b6e39e2df.png)

**Desktop (please complete the following information):**
 - OS = Windows 10 20H2 19042.631
 - .NET version =  4.8.04084
 - Version = v9.4.2

**Comment by dapal-003** [comment]
Dark lotus itself is supported, as in the data to handle it is there, but due to the fact it's so similar to other colors on screen the scan result is a lot worse than with other themes. I recommend you go back to Stalker as it's one of, if not the best theme for text detection. Zephyr and Viviturian both work well too
