### ISSUE TITLE
Nova prime blueprint but display braton prime blueprint and log says nova

### ISSUE THREAD

**Issue by neyna** [WFCD/WFinfo#228]
I had a nova prime blueprint displayed as braton prime blueprint and strange thing it seems it was detected correctly but was changed : 

[30/01/2022 23:43:00 9.4.2]   Found part(0): "Astilla Prime Stock" from "AstillaPrimeStock"
[30/01/2022 23:43:00 9.4.2]   Found part(8): "Braton Prime Blueprint" from "prhloatPNovaPrimeBlueprint"
[30/01/2022 23:43:00 9.4.2]   Found part(0): "Guandao Prime Blade" from "GuandaoPrimeBlade"
[30/01/2022 23:43:00 9.4.2]   Found part(0): "Lex Prime Barrel" from "LexPrimeBarrel"

**Comment by D1firehail** [comment]
Usually the preferred means to report issues in WFInfo is to do it on the discord, as communication is faster and more detailed debugging info can be sent with better privacy in private text channels. There's an invite link at the bottom of the readme and there's a button for in inside of WFInfo

As you can see, it did not read "NovaPrimeBlueprint", it read "prhloatPNovaPrimeBlueprint". 
The "prhloatP" is almost certainly from junk that got past the filtering process due to being very similar in colour to the actual text and happened to get incorrectly picked up by the OCR (text recognition). As it happens, with that extra junk the fuzzy matching is just as close between Braton Prime Blueprint and Nova Prime Blueprint so it just came down to order in the list.

**Comment by neyna** [comment]
Thanks for looking at this so fast.
I will report things like that in discord from now on.
