### ISSUE TITLE
GeForce Now Support

### ISSUE THREAD

**Issue by ChristopherKlay** [WFCD/WFinfo#260]
With Warframe being supported on GeForce Now for a while now, would it be possible to add support for the GFN version?

Detection of the window/game is fairly simple and i'd love to make use of this while streaming the game (:

**Comment by dimon222** [comment]
Sadly it's not a detection problem, but the picture noise that affects color palette. It ends up failing to detect correct theme that you're using and as result applies inefficient monochrome conversion algo that belongs to another theme.

**Comment by ChristopherKlay** [comment]
Would it be possible to manually select the used theme, in case GFN is detected?

**Comment by dimon222** [comment]
Since noise/artifacts affect the source, knowing theme is not enough. Cleaning all this noise isn't something we're very good at.

**Comment by D1firehail** [comment]
Once or twice in the past, we've had people using GFN test versions of WFInfo with the theme hardcoded. It didn't work due to the streaming compression affecting the colours too much. 

If user-tunable custom colour filters are ever implemented, that may work for GFN under good/stable conditions, but the noise level and colours could change very quickly in response to connection quality.
